vetiver_write_lambda_runtime <- function(board,
                                         name,
                                         version = NULL,
                                         ...,
                                         file = "runtime.R") {

    lambdr_dots <- rlang::list2(...)

    if (board$versioned) {
        if (is_null(version)) {
            version <- pins::pin_versions(board, name)
            version <- choose_version(version)
        }
        pin_read <- glue('v <- vetiver_pin_read(b, "{name}", version = "{version}")')
        v <- vetiver_pin_read(board, name, version = version)
    } else {
        pin_read <- glue('v <- vetiver_pin_read(b, "{name}")')
        v <- vetiver_pin_read(board, name)
    }

    load_infra_pkgs <- glue_collapse(glue("library({lambdr_infra_pkgs})"), sep = "\n")

    board <- rlang::expr_deparse(pins::board_deparse(board))
    board <- glue('b <- {board}')

    if (rlang::is_empty(lambdr_dots)) {
        start_lambda <- "start_lambda()"
    } else {
        start_lambda <- expr(start_lambda(!!!lambdr_dots))
        start_lambda <- expr_deparse(start_lambda)
    }

    handler <- glue("\n
        vetiver_predict <- function(...) {{
            predict(v, as.data.frame(...))
        }}
        ")

    pins_tempfile_fix <- glue::glue("\n
        # Required to stop pins from trying to write to the home directory
        # See https://github.com/rstudio/pins-r/issues/611
        Sys.setenv(R_USER_CACHE_DIR = tempfile())
        Sys.setenv(R_USER_DATA_DIR = tempfile())
        \n")

    ret <- compact(list(
        "# Generated by the vetiver package; edit with care\n",
        load_infra_pkgs,
        pins_tempfile_fix,
        board,
        pin_read,
        handler,
        start_lambda
    ))
    readr::write_lines(ret, file = file)
}

lambdr_infra_pkgs <- c("pins", "lambdr", "vetiver")

vetiver_write_lambda_docker <- function(vetiver_model,
                                        runtime_file = "runtime.R",
                                        handler = "vetiver_predict",
                                        path = ".",
                                        lockfile = "vetiver_renv.lock",
                                        rspm = TRUE) {

    parent <- "FROM public.ecr.aws/lambda/provided"

    r_version <- getRversion()
    # epel: Extra Packages for Enterprise Linux (dependencies required for R)
    epel <- "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

    # required to download and untar R and R binaries
    install_wget_and_tar <- glue::glue("RUN yum -y install wget tar")

    install_r <- glue::glue(
        "RUN yum -y install {epel} && \\\n",
        "  wget https://cdn.rstudio.com/r/centos-7/pkgs/R-{r_version}-1-1.x86_64.rpm && \\\n",
        "  yum -y install R-{r_version}-1-1.x86_64.rpm && \\\n",
        "  rm R-{r_version}-1-1.x86_64.rpm",
        .trim = FALSE
    )

    put_r_in_path <- glue::glue('ENV PATH="${{PATH}}:/opt/R/{r_version}/bin/"')

    set_cran_mirror <- glue::glue(
        "RUN echo 'options(repos = c(CRAN = \"https://cran.rstudio.com/\"))' >> /opt/R/{r_version}/lib/R/etc/Rprofile.site"
    )

    rspm_env <- ifelse(
        rspm,
        "ENV RENV_CONFIG_REPOS_OVERRIDE https://packagemanager.rstudio.com/all/__linux__/centos7/latest\n",
        ""
    )

    pkgs <- unique(c(lambdr_packages, vetiver_model$metadata$required_pkgs))

    renv::snapshot(
        project = path,
        lockfile = lockfile,
        packages = pkgs,
        prompt = FALSE,
        force = TRUE
    )

    runtime_file <- fs::path_rel(runtime_file)
    sys_reqs <- glue_sys_reqs(pkgs, distribution = "centos", release = "7")
    copy_renv <- glue("COPY {lockfile} renv.lock")
    copy_runtime <- glue("COPY {runtime_file} /opt/ml/runtime.R")
    create_bootstrap <- (
    "RUN printf '#!/bin/sh\\nRscript /opt/ml/runtime.R' > /var/runtime/bootstrap \\
        && chmod +x /var/runtime/bootstrap"
    )

    entrypoint <- glue::glue('CMD ["{handler}"]')

    ret <- compact(list(
        "# Generated by the vetiver package; edit with care\n",
        ## https://github.com/rstudio/plumber/blob/main/Dockerfile:
        parent,
        install_wget_and_tar,
        install_r,
        put_r_in_path,
        set_cran_mirror,
        rspm_env,
        sys_reqs,
        'RUN Rscript -e "install.packages(\'renv\')"',
        copy_renv,
        'RUN Rscript -e "renv::restore()"',
        copy_runtime,
        create_bootstrap,
        entrypoint
    ))

    readr::write_lines(ret, file = file.path(path, "Dockerfile"))
}

lambdr_packages <- c("pins", "vetiver", "renv", "paws.storage",
                     "lambdr", "httr", "jsonlite", "logger")
